### ISSUE TITLE
AliyunOSSFS 不能写入？

### ISSUE THREAD

**Issue by hongtao12310** [videome/AliyunOSSFS#1]
hello，

我运行了这个ossfs。发现能够成功挂载并能够读里面的内容 但是我向里面写的时候就出现了问题

比如 我用cp命令向mount folder 拷贝一个文件
cp readme mntoss/

是我命令用错了吗？还是write接口没有开发？

报的错误如下：
aliyun-oss-fs> 10月 12, 2015 1:47:01 上午 com.aliyun.oss.common.comm.ServiceClient sendRequestImpl
警告: Unable to execute HTTP request: Not Found

10月 12, 2015 1:47:01 上午 com.aliyun.oss.common.comm.ServiceClient sendRequestImpl
警告: Unable to execute HTTP request: Not Found

2015-10-12 01:47:01 [Thread-445] ERROR c.g.z.aliyunoss.AliyunOSSFilesystem - Can not find path '/README.md'

**Comment by zxkane** [comment]
是的，是此实现不支持写入。我的本意就是做一个**readonly**的目录挂载点，用于备份数据。

如果你需要写入支持，可以看看[这个实现](http://git.oschina.net/weiweibaba2007/cloudfs).

**Comment by zxkane** [comment]
work as design

**Comment by hongtao12310** [comment]
好的 非常感谢你的回复 你给我的这个链接挺好用的

我的平台是centos7  能够运行的很好

对了 他这个项目有放到git hub上面吗？现在有人在持续更新没？

以后我们碰到问题可以多交流 ：）

在 2015-10-12 17:19:47，"Meng Xin Zhu" notifications@github.com 写道：

是的，是此实现不支持写入。我的本意就是做一个readonly的目录挂载点，用于备份数据。

如果你需要写入支持，可以看看这个实现.

—
Reply to this email directly or view it on GitHub.

## 

  Best Regards
  Tao

**Comment by zxkane** [comment]
这个软件应该没有开源在github。

它是阿里云某合作公司开发。
http://market.aliyun.com/products/52738003/cmgj000304.html?spm=5176.383663.9.21.qjwkzk

但开源做的并不正规，release跟开源的代码之间没有明确对应。

我写这个java实现的时候，因为这个软件当时并没有开源版本。出于安全考虑，没敢用。国内的软件环境大家都懂。

Kane

2015-10-13 17:19 GMT+08:00 hongtao12310 notifications@github.com:
